version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./examplestore.db:/app/examplestore.db
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/app/examplestore.db
    container_name: go-backend

  db:
    image: sqlite3:latest
    volumes:
      - ./examplestore.db:/data/examplestore.db
    container_name: sqlite-db
    command: ["sqlite3", "/data/examplestore.db"]
